### ISSUE TITLE
install necessary packages for using a CGO-extension compiled version of Hugo

### ISSUE THREAD

**Issue by fool** [netlify/build-image#183]
When attempting to run a new hugo build, it seems we are missing some dependencies:

```
6:20:18 PM: Executing user command: ./hugo --config paceup.com.toml,config.toml
6:20:18 PM: ./hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./hugo)
6:20:18 PM: ./hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./hugo)
```

We need to install whatever is needed here :)

**Comment by fool** [comment]
Should notify these customers in our helpdesk:

-  https://app.intercom.io/a/apps/q245f50x/inbox/inbox/unassigned/conversations/17497593067

**Comment by regisphilibert** [comment]
Untill then it’s hard to mention Netlify (let alone use it) alongside Hugo Pipes... too bad because speeding up deployement is among the big pros 😔

**Comment by DirtyF** [comment]
@regisphilibert https://hugoscss.netlify.com/ :)

**Comment by regisphilibert** [comment]
@DirtyF this repo commits its resources directory. It’s really not ideal if the assets can be edited by an editor.

**Comment by regisphilibert** [comment]
Hi @oncletom, let's take this here: https://discourse.gohugo.io/t/netlify-and-hugo-pipes/13145

**Comment by jhabdas** [comment]
If Netlify's CI supports Docker the following Dockerfile should get you up and running. Builds Hugo from source. Set CGO env var from file or override via CLI:

https://git.habd.as/comfusion/after-dark/src/branch/master/docker/hugo/Dockerfile

**Comment by brycekahle** [comment]
Appears it was intended to be a dynamically linked binary: https://github.com/gohugoio/hugo/issues/4985

**Comment by jensamunch** [comment]
this doesn't work still for hugo 0.46

what is the best thread for tracking this issue and netlify using the extended version?

**Comment by brycekahle** [comment]
@jensamunch This issue is tracking it.

**Comment by fool** [comment]
hugo 0.46 works well for me - just can't use the extended version, right @jensamunch ?

**Comment by oncletom** [comment]
I did not fully grasp _why_ installing this specific version of `libstdc++` solves the problem but this message on Hugo forums explains how to install a version of `libstdc++` which is picked up by Hugo and works with the extended build: https://discourse.gohugo.io/t/solved-hugo-v44-extended-and-relocation-errors-on-travis/13029/5

**Comment by baublet** [comment]
Ping for visibility. As of Hugo 0.47.1, extended still won't work on Netlify due to two reasons:

1. The default binary Netlify uses is not the extended binary
2. The Netlify image needs the required dependencies (see @oncletom's comment above) to run the extended binary.

**To those looking for a workaround until this is fixed:**

Run `hugo` locally with the extended version, then check in your `resources/_gen/assets` directory to the repository so that Hugo skips trying to generate the assets.

**Comment by jhabdas** [comment]
According to Worldometers the [current population in China](http://www.worldometers.info/world-population/china-population/) is 1,415,971,400 and the [world population](http://www.worldometers.info/world-population/) is 7,646,606,545. Therefore, approximately 18% of the world population is not able to access Netlify build logs.

**Comment by jhabdas** [comment]
According to Worldometers the [current population in China](http://www.worldometers.info/world-population/china-population/) is 1,415,971,400 and the [world population](http://www.worldometers.info/world-population/) is 7,646,606,545. Therefore, approximately 18% of the world is not able to access Netlify build logs.

**Comment by sshesh** [comment]
I installed hugo through snap and a recent version (0.47.1) works well for me.

$ snap list
Name  Version  Rev   Tracking  Publisher     Notes
core  16-2.35  5328  stable    canonical*    core
hugo  0.47.1   2590  stable    hugo-authors  -

**Comment by igk1972** [comment]
Fast workaround for Hugo extended version.

package.json
```javascript
{
    // ...
    "scripts": {
      "prepare": "netlify-build-fix.sh",
      // ...
    },
   //  ...
}
```

netlify-build-fix.sh
```shell
#!/bin/bash

HUGO_FLAVOUR="hugo_extended"
HUGO_VERSION="0.48"

[ -z "${NF_IMAGE_VERSION}" ] && exit 0

rm -fr *.deb 
wget --no-clobber http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb || exit 1
wget --no-clobber https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.deb || exit 1
grep "hugo=" ~/.bashrc || echo "alias hugo='LD_LIBRARY_PATH=$(pwd)/tmp/usr/lib/x86_64-linux-gnu $(pwd)/tmp/usr/local/bin/hugo'" >> ~/.bashrc 
find -name '*.deb' -exec dpkg -x {} $(pwd)/tmp \;
rm -fr *.deb

exit 0
```

**Comment by bep** [comment]
Doing `ldd --version` in a Netlify script gets this:

```bash
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.13) 2.19
12:28:30 AM: Copyright (C) 2014 Free Software Foundation, Inc.
12:28:30 AM: This is free software; see the source for copying conditions.  There is NO
12:28:30 AM: warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
12:28:30 AM: Written by Roland McGrath and Ulrich Drepper.
```

This is a Ubuntu from 4 years+ ago. Debian and Ubuntu have since moved from EGLIBC to GLIBC -- which should work fine with the extended Hugo version. If not, let me know and I will look into it quickly from the Hugo side of it.

/cc @biilmann

**Comment by fool** [comment]
Yup, we're still running Ubuntu 14.04 LTS in the build environment.  in 8
months or so it will end of life, and we'll move before then.  We don't
expect you to tailor things for it in the meantime, @bep!  It's just a
challenge to move our hundreds of thousands of customers without breaking
many builds so we're working on a smoother way to do that and that's taking
awhile.

**Comment by fool** [comment]
To summarize the currently available workarounds:

1. recommended, follow bep's advice here:  https://discourse.gohugo.io/t/netlify-and-hugo-pipes/13145 - summarized in the thread on this issue here:  https://github.com/netlify/build-image/issues/183#issuecomment-415884055
2. not recommended but may work for you:  https://github.com/netlify/build-image/issues/183#issuecomment-419199649

**Comment by bcomnes** [comment]
Since this is solved in the xenial image and isn't easily solvable in the trusty image, I'm going to close this issue.  We should have that image out to everyone soonish.

**Comment by RealOrangeOne** [comment]
@bcomnes surely that means this issue is still valid? It's not actually solved until the xenial-based image has shipped

**Comment by aborruso** [comment]
@baublet you have writtern 

> **To those looking for a workaround until this is fixed:**
> 
> Run `hugo` locally with the extended version, then check in your `resources/_gen/assets` directory to the repository so that Hugo skips trying to generate the assets.

I'm a newbie: what's the menaning of "check in your `resources/_gen/assets` directory to the repository so that Hugo skips trying to generate the assets". What I must set in my repo and in netlify?

Thank you

**Comment by regisphilibert** [comment]
> I'm a newbie: what's the menaning of "check in your `resources/_gen/assets`

Hugo will not "generate" resources if they are found in `resources/_gen/assets`. So make sure the `resources/_gen/assets` is indexed by git.  Then build your sass resources locally (running `hugo`), commit resources change and push.

This does mean you need to run hugo locally when changing your scss file.

There's nothing to do on Netlify's hand.

**Comment by bcomnes** [comment]
@RealOrangeOne the issue, from the perspective of this issue tracker, is closed, in that the work needed to get the code working in this repo on `master` is completed, and all available workarounds we can add to a 14.04 image thats currently deployed publicly.  

Again, apologies for this taking so long to get out, we are currently working on infrastructure that will dramatically decrease the update cadence for build-images.

When it is shipped, we will be publicly announcing it on our blog and twitter.  If you want super duper early access, I can arrange that as well.

**Comment by jaysee00** [comment]
This also seems to be happening for anyone who tries to use the `nodegit` package as part of their build command:

```
 Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not   found (required by /opt/build/repo/node_modules/nodegit/build/Release/nodegit.  node)
```

See https://github.com/nodegit/nodegit/issues/853

**Comment by newsch** [comment]
I just checked in on this again, and found that [the Xenial image is available for use](https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/). I didn't see any mention of it here so I figured I'd leave a comment.
Sass compilation worked fine for me after changing the build image!

**Comment by beausmith** [comment]
I can confirm. I switched to the build image to `Ubuntu Xenial 16.04 (default)` and was able to successfully build and hugo with sass/scss on netlify…

![image](https://user-images.githubusercontent.com/28444/69001350-9584a600-0891-11ea-9738-3649e8897052.png)

**Comment by wmerussi** [comment]
Updated the build image selection like @beausmith and `netlify.toml` with the content from [hugo website](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) and now it's back online :)
